

POST http://localhost:3000/cart
Content-Type: application/json
Cart-Token: xxxx

{
  "product_id": 1,
  "quantity": 2
}

###

GET http://localhost:3000/cart
Cart-Token: 2fe6206fbed31b7052bd8ea344180b59
Content-Type: application/json

###

POST http://localhost:3000/cart/add_item
Cart-Token: 2fe6206fbed31b7052bd8ea344180b59
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 5
}

###

DELETE http://localhost:3000/cart/2
Cart-Token: 2fe6206fbed31b7052bd8ea344180b59
Content-Type: application/json

